version: "3.9"
   
services:
  web:
    build: .
    volumes:
      - .:/usr/src/app
    ports:
      - "8080:8080"
    environment:
      - DB_NAME=shopping_cart
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=defaultpass
    depends_on: 
      - db

  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: defaultpass
      MYSQL_DATABASE: shopping_cart
    ports:
      - "3306:3306"